version: '3.8'
services:
  biddify-product-database:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=biddify
    networks:
      - biddify
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d

  biddify-product-db-admin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: biddify-product-database
    depends_on:
      - biddify-product-database
    networks:
      - biddify

  biddify-product-node.js:
    image: robfontys/biddify-product-node.js
    ports:
      - "3002:3002"
    environment:
      DB_HOST: biddify-product-database
      DB_USER: root
      DB_PASSWORD: biddify
      DB_DATABASE: biddify
      DB_PORT: 3306
      DB_DIALECT: mysql
    restart: on-failure
    depends_on:
      - biddify-product-database
    networks:
      - biddify

  biddify-react.js:
    image: robfontys/biddify-react.js
    ports:
      - "3001:3001"
    depends_on:
      - biddify-product-node.js
    networks:
      - biddify
    command: npm start
    stdin_open: true

networks:
  biddify: